### ISSUE TITLE
th-desugar 1.8 fails with ghcjs

### ISSUE THREAD

**Issue by matthewbauer** [goldfirere/th-desugar#119]
Running the th-desugar test suite with ghcjs 8.4, gives me this error:

```
Test/DsDec.hs:69:3: error:
    The exact Name ‘MkGInt_aoZR’ is not in scope
      Probable cause: you used a unique Template Haskell name (NameU),
      perhaps via newName, but did not bind it
      If that's it, then -ddump-splices might be useful
   |
69 | $(dsDecSplice S.dectest12)
   |   ^^^^^^^^^^^^^^^^^^^^^^^

Test/DsDec.hs:69:3: error:
    The exact Name ‘MkGInt_aoZR’ is not in scope
      Probable cause: you used a unique Template Haskell name (NameU),
      perhaps via newName, but did not bind it
      If that's it, then -ddump-splices might be useful
   |
69 | $(dsDecSplice S.dectest12)
   |   ^^^^^^^^^^^^^^^^^^^^^^^

Test/DsDec.hs:69:3: error:
    The exact Name ‘MkGOther_aoZS’ is not in scope
      Probable cause: you used a unique Template Haskell name (NameU),
      perhaps via newName, but did not bind it
      If that's it, then -ddump-splices might be useful
   |
69 | $(dsDecSplice S.dectest12)
   |   ^^^^^^^^^^^^^^^^^^^^^^^

Test/DsDec.hs:69:3: error:
    The exact Name ‘MkGOther_aoZS’ is not in scope
      Probable cause: you used a unique Template Haskell name (NameU),
      perhaps via newName, but did not bind it
      If that's it, then -ddump-splices might be useful
   |
69 | $(dsDecSplice S.dectest12)
   |   ^^^^^^^^^^^^^^^^^^^^^^^
```

Reproduced the same thing in a project using th-desugar via singletons as well.

Looks to be similar to this issue:

https://github.com/ghcjs/ghcjs/issues/617

Maybe also related to this:

https://github.com/ghcjs/ghc/commit/f1a393ae03d7310159d27e146197d1fd99242aac

**Comment by RyanGlScott** [comment]
This looks strikingly similar to glguy/th-abstraction#53, which in turn is an occurrence of [GHC #15481](https://gitlab.haskell.org/ghc/ghc/issues/15481). That issue was fixed in GHC 8.6.2—is there a way test if using that version of GHC + GHCJS fixes your issue? (I'm not familiar with GHCJS, so apologies if this is not feasible.)

**Comment by RyanGlScott** [comment]
For what it's worth, I can trigger this error on GHC 8.4.4 if I run the `th-desugar` test suite with `-fexternal-interpreter`, but not with GHC 8.6.5 + `-fexternal-interpreter`. According to https://github.com/glguy/th-abstraction/issues/53#issuecomment-410652582, `-fexternal-interpreter` is a pretty close approximation of how GHCJS handles Template Haskell, so that is an encouraging sign.

Then again, I'm not running GHCJS directly, so it's hard to say with 100% certainty. I'd like to get a confirmation on your end before I deem this issue fixed.

**Comment by matthewbauer** [comment]
Thanks! that's really helpful. Trying to see if that patch fixes the issue in ghcjs. Unfortunately I'm stuck on ghc/ghcjs 8.4 for the time being.
